### PR TITLE
Require at least Maven 3.0 for jacoco-maven-plugin

### LINKED ISSUE #194: Revoke support for Maven 2.2.*
As decided on the Maven developer list, Maven 2.2.\* has reached [end-of-life](http://mail-archives.apache.org/mod_mbox/maven-dev/201402.mbox/%3CCA%2BnPnMzPNhkBqbj-Uz045Gt4j8%3DCiXBFCwnNGB0NZ38j-X%2BUvA%40mail.gmail.com%3E).

We may choose between 2 strategies:
1. Just do not fix any Maven 2.2.\* related issues and do not test jacoco-maven-plugin with this version anymore.
2. Go forward and make Maven 3.\* a prerequisite for building jacoco _and_ running the `jacoco-maven-plugin` _and_ remove any workarounds and documentation for running jacoco with Maven 2.2.*

@Godin, @marchof: your oppinions?

### PR DESCRIPTION
**Pull request by slachiewicz**
Fixes #194

Tests with Java 5 failed due to artifact doxia-site-renderer-1.7.4 compiled for Java 6 (from maven-reporting-impl:jar:3.0.0) - blocked by #314

### CODE REVIEW

**Comment by Godin** [comment]
@slachiewicz thank you for your contribution - it is good to know about connection between #194 and #314 👍 However #314 was not in our short-term plans and #194 is definitely not enough to justify #314 - Maven is not the only way of JaCoCo usage. Is there a chance that you can work on a way to resolve this without #314 ? If not, then we would prefer to close this incomplete PR.

**Comment by slachiewicz** [comment]
Unfortunately, I don't see any reasonable solution, because maven-reporting-impl is required for reporting functionality. 
@khmarbaise maybe You have an idea?

**Comment by Godin** [comment]
In fact sounds strange that #194 requires #314 , because according to page https://maven.apache.org/docs/history.html Maven 3.0 was still on Java 5 😉 @slachiewicz are you sure that update of `maven-reporting-impl` is needed?

**Comment by Godin** [comment]
@marchof are you ok if in upcoming release we drop support of Maven 2.2.1 (last release in November 2009) ? If so, then I'll take care of further testing, review of documentation, etc to finalize this PR.

**Comment by Godin** [comment]
@marchof I updated documentation and IMO this is ready to be merged.

**Pull request merged**
