### PR TITLE
Add FAQ entry about class filtering in reports

### PR DESCRIPTION
**Pull request by marchof**

### CODE REVIEW

**Comment by Godin** [comment]
@marchof addition of such entry into FAQ is nice since this indeed seems to be a quite frequent source of questions, and so I'm wondering - WDYT maybe text on other page(s) (such as [page about agent](https://www.jacoco.org/jacoco/trunk/doc/agent.html)) can be somehow improved? I'm ok to merge this PR as it is if you don't have ideas for other pages.

**Comment by Godin** [comment]
Rephrasing a bit my question - maybe source of questions is misunderstanding due to not very clear text of text on other pages?

**Comment by marchof** [comment]
@Godin Agreed, FAQ entry is a symptom for lack of documentation. I'll give it a try.

**Comment by marchof** [comment]
@Godin I added hints at the respective doc pages (only to the exclude options). Is this what you were thinking about?

**Comment by Godin** [comment]
@marchof yup! :thumbsup:

**Pull request merged**
