### PR TITLE
Document `includeCurrentProject` available as of 0.8.9

### PR DESCRIPTION
**Pull request by MikeEdgar**
Follow-up to https://github.com/jacoco/jacoco/pull/1007. The new `includeCurrentProject` that has yet to be released is listed in the documentation as available since release 0.7.7.

### CODE REVIEW

**Comment by MikeEdgar** [comment]
Question to the maintainers: do you anticipate a 0.8.9 release soon or is it yet to be determined? Our team would like to use `includeCurrentProject`, however we'll take a different approach if a release is not happening for a while. Thanks

**Review by marchof — APPROVED** [review]

**Comment by marchof** [comment]
@MikeEdgar We will release 0.8.9 soon for official Java 19 support.

**Comment by Thilaknath** [comment]
@marchof Following this. When is this slated for release ?

**Comment by fr-penghuang** [comment]
> Question to the maintainers: do you anticipate a 0.8.9 release soon or is it yet to be determined? Our team would like to use `includeCurrentProject`, however we'll take a different approach if a release is not happening for a while. Thanks

hi @MikeEdgar 
we‘re also waiting for the release, would you mind share your approach if a release is not happening for a while.

**Comment by MikeEdgar** [comment]
> would you mind share your approach if a release is not happening for a while

Nothing yet 😂. perhaps use the latest snapshot if you're waiting on the feature this PR relates to.

**Comment by MikeEdgar** [comment]
@marchof , since this is just a documentation change, is there any reason it can not be merged sooner? I think it would save many people the time of testing/debugging the plugin since `includeCurrentProject` is advertised as having been available since version 0.7.7 [1].

[1] https://www.jacoco.org/jacoco/trunk/doc/report-aggregate-mojo.html

**Pull request merged**
