### PR TITLE
Adding new filter for methods annotated with @kotlin.Generated by Kotlin compiler

### PR DESCRIPTION
**Pull request by andreyfomenkov**
The related PR in JetBrains repository: [#1655](https://github.com/JetBrains/kotlin/pull/1655)
Could be a good start to solve this opened issue: **_Recognize and ignore Kotlin-generated code_** #552 
Post on Medium: [Kotlin + JaCoCo: Tuning Compiler to Skip Generated Code.](https://medium.com/@andrey.fomenkov/kotlin-jacoco-tuning-compiler-to-skip-generated-code-935fcaeaa391)

### CODE REVIEW

**Comment by marchof** [comment]
@andreyfomenkov Thanks for this contrubution! Which Kotlin compiler will emit this annotation? It must be clear to our users which version of the compiler they need to use to get this feature here. Otherwise we will get lots of questions here...

**Comment by JLLeitschuh** [comment]
@andreyfomenkov Your post on Medium seems to indicate you need a custom version of the Kotlin compiler for this to work? Is there any chance you could get your change into the Jetbrains official compiler?

**Comment by andreyfomenkov** [comment]
@marchof only after merge the upcoming PR to JetBrains I can tell the compiler version and supported features.
@JLLeitschuh the fork was created just for experimenting. Of course all changes should be merged into the official repo. Well, can't promise everything, but I'll do my best :blush:

**Comment by marchof** [comment]
@andreyfomenkov Ok, so in this case please understand that we cannot merge this until we know the corresponding Kotlin release which generates the annotation. This version should then also be mentioned in the change log.

**Comment by andreyfomenkov** [comment]
@marchof sure :+1: , let's keep this pull request until we get updates from JetBrains.

**Comment by JLLeitschuh** [comment]
@andreyfomenkov Can you link to the Jetbrains Kotlin repo PR in the top description of this PR?

**Comment by andreyfomenkov** [comment]
@JLLeitschuh I've added link into PR description. Need to investigate failed tests for the compiler.

**Comment by andreyfomenkov** [comment]
I'll close this PR because the related changes in JetBrains repository were declined and now considered as a reserve solution. But let's keep it just in case.

**Pull request closed without merging**
