### PR TITLE
Add missing test case that is described in documentation

### PR DESCRIPTION
**Pull request by Godin**
This adds test case that is described on page http://www.eclemma.org/jacoco/trunk/doc/flow.html :

> ..  implicit exceptions from other instructions than method invocations (e.g. NullPointerException ...

And removes misleading comments

> Currently no coverage at all, as we don't see when a block aborts somewhere in the middle.

from the cases, where we actually see some coverage, when block aborts in the middle.

### CODE REVIEW

**Comment by marchof** [comment]
@Godin Not sure why a single build (9-ea-stable) fails. Can you please check and merge?

**Comment by Godin** [comment]
@marchof from time to time `testInvalidCommand(org.jacoco.agent.rt.internal.output.TcpClientOutputTest)` fails in Travis, I don't know why - race condition, timeouts or something like that.

**Comment by marchof** [comment]
@Godin can we trigger a manual build so we can merge this?

**Comment by Godin** [comment]
@marchof yup - I restarted build already

**Pull request merged**
