### PR TITLE
Add aggregate-report that reports cross module code coverage for the maven plugin

### PR DESCRIPTION
**Pull request by johnoliver**
We have had issues with gaining accurate cross module code coverage numbers with jacoco. For instance when code in module A is touched during tests from module B, in our case when they are both part of a multi-module build.

This pull request makes it possible to report coverage numbers on classes outside of the current module. By adding a list of sourceFolders and classFolders which is a list of source and class folders outside of the current module to be scanned for classes to report coverage on.

The aggregate-report then concatenates the jacoco.exec files from reactor projects so that a unified report can be created.

### CODE REVIEW

**Comment by paranoiabla** [comment]
+1 still waiting for this...

**Comment by jivenorris** [comment]
This would be useful.

**Comment by rajneeshpatel** [comment]
+1

**Comment by pveentjer** [comment]
+1 

We would also like the ability to see the test coverage in module A, caused by tests in module B. So just merging is not sufficient.

**Comment by raysuliteanu** [comment]
+1

**Comment by jimfcarroll** [comment]
+1

**Comment by bkmeneguello** [comment]
+1 What is the status of this feature? Is it at least approved?

**Comment by marchof** [comment]
@bkmeneguello Absolutely! We just need someone who picks-up the work to review and finalize this, probably also considering #69

**Comment by bgard6977** [comment]
+1 Need this

**Comment by RawToast** [comment]
+1, this avoids completing a nasty maven setup to complete the same job.

**Comment by Donnerbart** [comment]
+1 Could someone please take care of this?

**Comment by handcraftedbits** [comment]
+1, need this badly.

**Comment by bgard6977** [comment]
To everyone here, please look in to Cobertura... it can get you what you want.

**Comment by ansell** [comment]
@bgard6977 Do you have a code example of using cobertura-maven-plugin to do this?

**Comment by bgard6977** [comment]
<plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>cobertura-maven-plugin</artifactId>
                <version>${cobertura.version}</version>
                <configuration>
                    <check>
                        <haltOnFailure>true</haltOnFailure>
                        <branchRate>0</branchRate>
                        <lineRate>0</lineRate>
                        <totalBranchRate>0</totalBranchRate>
                        <totalLineRate>0</totalLineRate>
                        <packageLineRate>0</packageLineRate>
                        <packageBranchRate>0</packageBranchRate>
                    </check>
                    <aggregate>true</aggregate>
                    <formats>
                        <format>xml</format>
                        <format>html</format>
                    </formats>
                    <instrumentation>
                        <excludes>
                            <exclude>generated-classes/**/*.class</exclude>
                            <exclude>**/*IntegrationTest.class</exclude>
                        </excludes>
                    </instrumentation>
                </configuration>
            </plugin>

**Comment by iwhitfield** [comment]
@bgard6977 I don't think Cobertura accomplishes the same as this PR; this PR is aimed at cross-module coverage, whereas Cobertura cannot detect code touched by modules other than the module it lies within.

I might be mistaken, but that is a very big distinction.

**Comment by ansell** [comment]
@bgard6977 I only asked because I have not looked at Cobertura for a few years. The last time I looked, the multi-module code coverage (not simple aggregation of the reports from different modules) functionality was not in cobertura-maven-plugin, and hence not easily accessible. 

The use of aggregate=true looks like it is simple aggregation of the reports from different modules, based on the documentation of cobertura-maven-plugin that is fairly non-specific. That is not what this issue is focused on if that is all it does. The common use of the work "aggregate" has caused some confusion in the past in relation to these two separate issues. 

We want jacoco-maven-plugin to record test coverage from tests run in "moduletest", against code from modulea/moduleb/modulec/etc., to follow one of the popular maven module layouts where code is in modulea, moduleb, modulec, etc., and the tests are located separately in moduletest. 

The only method I have found is a four-stage process using both maven and ant (see link below). This does actually do what we want, but it is a massive pain to work with and hence why there are quite a few people who are very interested in having it fully run by maven alone.

https://thomassundberg.wordpress.com/2012/02/18/test-coverage-in-a-multi-module-maven-project/

**Comment by bgard6977** [comment]
@ansell , I'm not entirely sure. I suspect you are correct, but that is fine in our case - we are mostly concerned about unit test coverage, and that shouldn't span modules by definition. I'll look into it some more and make a post here if I find out.

Don't get me wrong, I'd love it if Jacoco did this. If this PR had been merged already, I'd have never have even bothered setting up Cobertura. As it stands, it looks like Cobertura is the way to go for my company at least.

**Comment by ouaibsky** [comment]
+1 Need this

**Comment by zxiiro** [comment]
+1, anyway we can get this in the near future?

**Comment by dtelaroli** [comment]
+1

**Comment by cedricvidal** [comment]
+1

**Comment by kossmoboleat** [comment]
+1

**Comment by tchan-ecofactor** [comment]
+1

**Comment by xpepper** [comment]
+1

**Comment by karianna** [comment]
@Godin - Do we continue discussion of this patch here or on a mailing list somewhere?

**Comment by Godin** [comment]
@karianna I answered on your message in mailing list.

**Comment by asukhyy** [comment]
+1

**Comment by adelinor** [comment]
+1
This feature is very important. Also it should *not assume* that maven modules have the root POM as a parent.

**Comment by arcuri82** [comment]
+1
This is really a critical feature. Integration tests by default should report transitive coverage of all modules in a project

**Comment by JLLeitschuh** [comment]
+1 Is there any good workarounds for the time being?
Note: I'm using jacoco as a gradle plugin.

**Comment by Lucas3oo** [comment]
@JLLeitschuh you can get aggregation in your Hudson/Jenkins build. That's what I have to use right now. 
I also think that you can export all the result files to SonarQube to get aggregation.

The drawback here is you need some more software/server to get this going.

But I think JaCoCo has some Ant tasks that can aggregate a report in HTML.
So in your build you can create separate "project" or what it is alled in Gradle that only purpose is to aggregate the result files into a HTML report.

**Comment by smaring** [comment]
+1 ... we would like to see this as well.  We are currently aggregating in Sonarqube, but our developers don't want to have to publish to Sonar in order to see the aggregate coverage on the their multi-module projects.  Why has John's pull request been sitting open for so long?  We left Cobertura because it was starting to feel like a dead project.

**Comment by JLLeitschuh** [comment]
**WORKAROUND**
Put this in your `build.gradle` **after** your `project` and `allProjects` declarations:

```groovy
/*
 * This is roughly based upon this post:
 * https://discuss.gradle.org/t/merge-jacoco-coverage-reports-for-multiproject-setups/12100/6
 */
task jacocoRootReport(type: JacocoReport, group: 'Coverage reports') {
    description = 'Generates an aggregate report from all subprojects'
    dependsOn(subprojects.test)

    additionalSourceDirs = files(subprojects.sourceSets.main.allSource.srcDirs)
    sourceDirectories = files(subprojects.sourceSets.main.allSource.srcDirs)
    classDirectories = files(subprojects.sourceSets.main.output)
    executionData = files(subprojects.jacocoTestReport.executionData)

    reports {
        html.enabled = true
        xml.enabled = true
    }

    doFirst {
        executionData = files(executionData.findAll { it.exists() })
    }
}
check.dependsOn jacocoRootReport
```

**Comment by ksperling** [comment]
Would be really good to have this feature. As a workaround, I'm currently using a groovy script with the GMaven plugin (groovy-maven-plugin:execute). The script is executed from a separate 'aggregate' module and combines coverage data for all projects that are part of the reactor build: https://gist.github.com/ksperling/57b81ea723e319967d24

**Comment by btaz** [comment]
+1

**Comment by bobkubista** [comment]
+1

**Comment by overheadhunter** [comment]
+1

**Comment by zxiiro** [comment]
I'm disappointed that there are so many +1's on this PR yet it appears there is no progress. What do we need to do to get this going forward?

**Comment by markuskreusch** [comment]
+1

**Comment by jawaharprasad** [comment]
Not sure why this is not merged yet.

**Comment by sideisra** [comment]
+1

**Comment by johnoliver** [comment]
For those interested I have updated the pull request to have merged with the latest 0.7.7-SNAPSHOT. So if you are using this patch you can upgrade to the latest version.

**Comment by subhodipp** [comment]
Can you please let me know how to generate this (which tag I need to put?)?

**Comment by RadoslawOsinski** [comment]
It looks as maven plugin is stuck for few years on simple problem. Do not get me wrong. I appreciate your work. Especialy "johnoliver" who tries to merge this feature. But in the meantime people are migrating to gradle which is growing faster. In example look at this link:
https://gist.github.com/aalmiray/e6f54aa4b3803be0bcac
Gradle users are solving problems in days instead of years.

+1 for merging this feature.

**Comment by kriazhev** [comment]
+1

**Comment by JLLeitschuh** [comment]
Dear god, people, please, stop using +1.
There's a new reaction system for that sort of thing.

**Comment by Donnerbart** [comment]
This request is so ancient (nevertheless important) that it doesn't deserve such a modern reaction system. The solution is to fix the issue, not to make the +1 less painful.

**Comment by marchof** [comment]
@johnoliver @Godin @mfriedenhagen 
I finally found some time to dive into this issue and did a detailed analysis of the issue together with @jwloka. We discussed different solutions and finally implemented a different approach in PR #388.

**Comment by marchof** [comment]
Fixed with #388.

**Pull request closed without merging**
