### PR TITLE
Do not add useless members into Java 8 interfaces that have only clinit and abstract methods

### PR DESCRIPTION
**Pull request by Godin**
`ProbeCounter.hasMethods` should be true for Java 8 interfaces only in case of presence of non-abstract methods.

### CODE REVIEW

**Comment by Godin** [comment]
@marchof could you please review?

**Comment by bjkail** [comment]
Looks good to me.  As a very minor comment, better grammar for changes.html would be "interfaces that have" ("that" is for discriminating, "which" is for annotating) :-).

**Comment by Godin** [comment]
@bjkail thx, fixed

**Comment by marchof** [comment]
@Godin Thx!

**Pull request merged**
