### PR TITLE
Fix build with Java >= 12 when option -Dbytecode.version is not provided

### LINKED ISSUE #1054: Build JaCoCo with Java >= 12 and without bytecode.version property
* JaCoCo version:  latest version (d60a5b2)
* Tool integration: Maven 3.6.3 and Java 13.0.2
* Steps: `mvn clean verify` or `mvn clean package`

### Expected behaviour
Build succeed 

### Actual behaviour
Build fail

If we don't provider `bytecode.version` property the modules `org.jacoco.core.test.validation.kotlin` and `org.jacoco.core.test.validation.scala` will set `bytecode.version` to 6 and the compilation will fail for Java >= 13.

output:
```
...
[INFO] --- maven-compiler-plugin:3.7.0:compile (default-compile) @ org.jacoco.core.test.validation.kotlin ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 14 source files to /private/tmp/jacoco-20200607-58321-1pvig7h/jacoco-0.8.5/org.jacoco.core.test.validation.kotlin/target/classes
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 0.8.5:
[INFO]
[INFO] JaCoCo ............................................. SUCCESS [  1.511 s]
[INFO] JaCoCo :: Core ..................................... SUCCESS [  8.395 s]
[INFO] JaCoCo :: Report ................................... SUCCESS [  4.301 s]
[INFO] JaCoCo :: Agent RT ................................. SUCCESS [  1.635 s]
[INFO] JaCoCo :: Agent .................................... SUCCESS [  2.350 s]
[INFO] JaCoCo :: Ant ...................................... SUCCESS [  3.331 s]
[INFO] JaCoCo :: Command Line Interface ................... SUCCESS [  3.361 s]
[INFO] JaCoCo :: Examples ................................. SUCCESS [  3.152 s]
[INFO] JaCoCo :: Maven Plugin ............................. SUCCESS [  6.734 s]
[INFO] JaCoCo :: Tests .................................... SUCCESS [  0.141 s]
[INFO] JaCoCo :: Test :: Core ............................. SUCCESS [  5.559 s]
[INFO] JaCoCo :: Test :: Core :: Validation ............... SUCCESS [  0.044 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 5 ........ SUCCESS [  2.098 s]
[INFO] JaCoCo :: Test :: Core :: Validation Kotlin ........ FAILURE [  5.242 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 7 ........ SKIPPED
[INFO] JaCoCo :: Test :: Core :: Validation Java 8 ........ SKIPPED
[INFO] JaCoCo :: Test :: Core :: Validation Groovy ........ SKIPPED
[INFO] JaCoCo :: Test :: Core :: Validation Scala ......... SKIPPED
[INFO] JaCoCo :: Test :: Report ........................... SKIPPED
[INFO] JaCoCo :: Test :: Agent RT ......................... SKIPPED
[INFO] JaCoCo :: Test :: Agent ............................ SKIPPED
[INFO] JaCoCo :: Test :: Ant .............................. SKIPPED
[INFO] JaCoCo :: Test :: Command Line Interface ........... SKIPPED
[INFO] JaCoCo :: Test :: Examples ......................... SKIPPED
[INFO] JaCoCo :: Test :: Maven Plugin ..................... SKIPPED
[INFO] JaCoCo :: Documentation ............................ SKIPPED
[INFO] JaCoCo :: Distribution ............................. SKIPPED
[INFO] root ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  48.144 s
[INFO] Finished at: 2020-06-07T15:44:16-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project org.jacoco.core.test.validation.kotlin: Compilation failure: Compilation failure:
[ERROR] Source option 6 is no longer supported. Use 7 or later.
[ERROR] Target option 6 is no longer supported. Use 7 or later.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.jacoco.core.test.validation.kotlin
```

after applying the following changes:
```diff
diff --git a/org.jacoco.core.test.validation.kotlin/pom.xml b/org.jacoco.core.test.validation.kotlin/pom.xml
index 468b6472..4eda0ef4 100644
--- a/org.jacoco.core.test.validation.kotlin/pom.xml
+++ b/org.jacoco.core.test.validation.kotlin/pom.xml
@@ -25,7 +25,6 @@
   <name>JaCoCo :: Test :: Core :: Validation Kotlin</name>
 
   <properties>
-    <bytecode.version>6</bytecode.version>
     <kotlin.version>1.3.61</kotlin.version>
   </properties>
 
```

output
```
...
[INFO] --- scala-maven-plugin:4.0.2:compile (compile) @ org.jacoco.core.test.validation.scala ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] Compiling 3 Scala sources and 3 Java sources to /private/tmp/jacoco-20200607-58321-1pvig7h/jacoco-0.8.5/org.jacoco.core.test.validation.scala/target/classes ...
[WARNING] [Warn] : bootstrap class path not set in conjunction with -source 6
[ERROR] [Error] : Source option 6 is no longer supported. Use 7 or later.
[ERROR] [Error] : Target option 6 is no longer supported. Use 7 or later.
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for root 0.8.5:
[INFO]
[INFO] JaCoCo ............................................. SUCCESS [  1.517 s]
[INFO] JaCoCo :: Core ..................................... SUCCESS [  8.442 s]
[INFO] JaCoCo :: Report ................................... SUCCESS [  4.499 s]
[INFO] JaCoCo :: Agent RT ................................. SUCCESS [  1.675 s]
[INFO] JaCoCo :: Agent .................................... SUCCESS [  2.395 s]
[INFO] JaCoCo :: Ant ...................................... SUCCESS [  3.501 s]
[INFO] JaCoCo :: Command Line Interface ................... SUCCESS [  3.416 s]
[INFO] JaCoCo :: Examples ................................. SUCCESS [  3.229 s]
[INFO] JaCoCo :: Maven Plugin ............................. SUCCESS [  6.814 s]
[INFO] JaCoCo :: Tests .................................... SUCCESS [  0.147 s]
[INFO] JaCoCo :: Test :: Core ............................. SUCCESS [  5.846 s]
[INFO] JaCoCo :: Test :: Core :: Validation ............... SUCCESS [  0.045 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 5 ........ SUCCESS [  2.110 s]
[INFO] JaCoCo :: Test :: Core :: Validation Kotlin ........ SUCCESS [  7.805 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 7 ........ SUCCESS [  1.704 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 8 ........ SUCCESS [  1.782 s]
[INFO] JaCoCo :: Test :: Core :: Validation Groovy ........ SUCCESS [  3.340 s]
[INFO] JaCoCo :: Test :: Core :: Validation Scala ......... FAILURE [  4.400 s]
[INFO] JaCoCo :: Test :: Report ........................... SKIPPED
[INFO] JaCoCo :: Test :: Agent RT ......................... SKIPPED
[INFO] JaCoCo :: Test :: Agent ............................ SKIPPED
[INFO] JaCoCo :: Test :: Ant .............................. SKIPPED
[INFO] JaCoCo :: Test :: Command Line Interface ........... SKIPPED
[INFO] JaCoCo :: Test :: Examples ......................... SKIPPED
[INFO] JaCoCo :: Test :: Maven Plugin ..................... SKIPPED
[INFO] JaCoCo :: Documentation ............................ SKIPPED
[INFO] JaCoCo :: Distribution ............................. SKIPPED
[INFO] root ............................................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:02 min
[INFO] Finished at: 2020-06-07T15:51:39-03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal net.alchim31.maven:scala-maven-plugin:4.0.2:compile (compile) on project org.jacoco.core.test.validation.scala: Execution compile of goal net.alchim31.maven:scala-maven-plugin:4.0.2:compile failed.: CompileFailed -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :org.jacoco.core.test.validation.scala
```

and after applying the following changes:
```diff
diff --git a/org.jacoco.core.test.validation.scala/pom.xml b/org.jacoco.core.test.validation.scala/pom.xml
index a9c1ef15..647dc44a 100644
--- a/org.jacoco.core.test.validation.scala/pom.xml
+++ b/org.jacoco.core.test.validation.scala/pom.xml
@@ -24,10 +24,6 @@
 
   <name>JaCoCo :: Test :: Core :: Validation Scala</name>
 
-  <properties>
-    <bytecode.version>6</bytecode.version>
-  </properties>
-
   <dependencies>
     <dependency>
       <groupId>${project.groupId}</groupId>

```

output:
```
[INFO] Reactor Summary for root 0.8.5:
[INFO]
[INFO] JaCoCo ............................................. SUCCESS [  1.575 s]
[INFO] JaCoCo :: Core ..................................... SUCCESS [  8.350 s]
[INFO] JaCoCo :: Report ................................... SUCCESS [  4.592 s]
[INFO] JaCoCo :: Agent RT ................................. SUCCESS [  1.691 s]
[INFO] JaCoCo :: Agent .................................... SUCCESS [  2.371 s]
[INFO] JaCoCo :: Ant ...................................... SUCCESS [  3.568 s]
[INFO] JaCoCo :: Command Line Interface ................... SUCCESS [  3.483 s]
[INFO] JaCoCo :: Examples ................................. SUCCESS [  3.236 s]
[INFO] JaCoCo :: Maven Plugin ............................. SUCCESS [  6.859 s]
[INFO] JaCoCo :: Tests .................................... SUCCESS [  0.143 s]
[INFO] JaCoCo :: Test :: Core ............................. SUCCESS [  6.098 s]
[INFO] JaCoCo :: Test :: Core :: Validation ............... SUCCESS [  0.052 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 5 ........ SUCCESS [  2.241 s]
[INFO] JaCoCo :: Test :: Core :: Validation Kotlin ........ SUCCESS [  7.486 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 7 ........ SUCCESS [  1.739 s]
[INFO] JaCoCo :: Test :: Core :: Validation Java 8 ........ SUCCESS [  1.805 s]
[INFO] JaCoCo :: Test :: Core :: Validation Groovy ........ SUCCESS [  3.031 s]
[INFO] JaCoCo :: Test :: Core :: Validation Scala ......... SUCCESS [  5.903 s]
[INFO] JaCoCo :: Test :: Report ........................... SUCCESS [  3.625 s]
[INFO] JaCoCo :: Test :: Agent RT ......................... SUCCESS [  7.160 s]
[INFO] JaCoCo :: Test :: Agent ............................ SUCCESS [  1.490 s]
[INFO] JaCoCo :: Test :: Ant .............................. SUCCESS [01:02 min]
[INFO] JaCoCo :: Test :: Command Line Interface ........... SUCCESS [  3.214 s]
[INFO] JaCoCo :: Test :: Examples ......................... SUCCESS [  1.697 s]
[INFO] JaCoCo :: Test :: Maven Plugin ..................... SUCCESS [  0.333 s]
[INFO] JaCoCo :: Documentation ............................ SUCCESS [  4.888 s]
[INFO] JaCoCo :: Distribution ............................. SUCCESS [  2.128 s]
[INFO] root ............................................... SUCCESS [  0.017 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:31 min
[INFO] Finished at: 2020-06-07T15:56:03-03:00
[INFO] ------------------------------------------------------------------------
```

IDK if the changes I proposed here will have bad side effects, I think these module don't need to set `bytecode.version` property since the property is already defined by module `org.jacoco.build` right ?

### PR DESCRIPTION
**Pull request by andrioli**
Fixes #1054

### CODE REVIEW

**Comment by andrioli** [comment]
Hey @marchof the build is green ✅ 

I was trying to created a GitHub Actions in my fork to show you the build problem but I created the PR here by mistake (see: https://github.com/jacoco/jacoco/pull/1056)

But the actions were executed here anyway: https://github.com/jacoco/jacoco/actions/runs/128828299

Look that the build failing for some newer Java versions. I was expecting to fail for Java >= 13 but in fact it's failing for Java >= 12 (Probably they dropped support to source/target 6 in Java 12 😄 )

The build is also failing for Java 7 in GitHub Actions, but look that is for another reason!

**Comment by andrioli** [comment]
> The build is also failing for Java 7 in GitHub Actions, but look that is for another reason!

Okay, you guys are enforcing the build with at least Java 8: `Detected JDK Version: 1.7.0-262 is not in the allowed range 1.8`. Compile with Java 7 only using Maven toolchains 👍

**Comment by marchof** [comment]
@Godin Can you please have a look at this?

**Comment by Godin** [comment]
> Probably they dropped support to source/target 6 in Java 12

@andrioli yes, support for `source` and `target` version `6` was removed in JDK 12 - see https://bugs.openjdk.java.net/browse/JDK-8028563

**Review by Godin — APPROVED** [review]
@andrioli 👍 tested locally with JDKs from 12 to 16 EA. Thank you for your contribution ❤️

**Review by marchof — APPROVED** [review]

**Pull request merged**
