### PR TITLE
Finalize documentation for PR #498

### PR DESCRIPTION
**Pull request by marchof**
Just a follow up to #498 to update documentation.

### CODE REVIEW

**Comment by marchof** [comment]
@Godin Can you please review? Thx

**Comment by Godin** [comment]
@marchof FYI I assume that was possible to update original PR #498 - see https://help.github.com/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork/

**Comment by marchof** [comment]
@Godin Thx for the hint! Next time I will try this.

**Comment by Godin** [comment]
And yeah - forgot to say thank you @okutane for contribution! :thumbsup:

**Comment by okutane** [comment]
@Godin more to come. (hope so :))

**Pull request merged**
