### PR TITLE
Added @NoCoverage

### PR DESCRIPTION
**Pull request by uweschaefer**
In order to consciously skip code from coverage measurement, @Generated can be used currently. We have the requirement of occasionally excluding code that is not exactly generated, but should be ignore for other reasons (Framework specific code etc). 
This is why we extended the behavior of @Generated also to code annotated with @NoCoverage.

Maybe this is useful for others as well.

### CODE REVIEW

**Comment by marchof** [comment]
Please see [PR675](https://github.com/jacoco/jacoco/pull/675#issuecomment-608075757) for a explanation why we cannot add this feature to JaCoCo.

As a side note @Godin suggested to use `@NoCoverageShouldBeGenerated` as a workaround as a distinct annotation 😉

**Comment by uweschaefer** [comment]
thank you for taking the time @marchof 

I understand and respect your decision on that. One thing though: I did not get the reference to @NoCoverageShouldBeGenerated. I don't see this annotation in jacocos codebase and i am a bit puzzled. Could you please point me to the code or discussion you are referenceing?

Thanks.

**Comment by Godin** [comment]
@uweschaefer quoting https://www.jacoco.org/jacoco/trunk/doc/changes.html

> Classes and methods annotated by annotation whose retention policy is runtime or class and whose simple name contains "Generated" (previously equality was required) are filtered out during generation of report (GitHub #822).

**Comment by uweschaefer** [comment]
thanks a lot, that'll help.

**Comment by Godin** [comment]
@uweschaefer please also note that `NoCoverageShouldBeGenerated` is an abuse of the feature that was developed for filtering of code generated by Lombok and Groovy and not for manual exclusions. Such abuse has the same bad consequences as https://github.com/jacoco/jacoco/pull/675#issuecomment-608075757 including #977 "does not work for lambda bodies in the annotated methods". As such any ticket/request related to such abuse might be closed as invalid.

**Comment by uweschaefer** [comment]
got that. However, it scratches an itch many users seem to have (looking at #675), so as long as it works (for the majority of cases), we'll probably make use of it, taking the consequences into account.
Thanks again.

**Pull request closed without merging**
