### PR TITLE
Property dataFileIncludes in report-aggregate is not changeable by pom due to known maven bug

### PR DESCRIPTION
**Pull request by Godin**
JaCoCo version: 0.7.7-SNAPSHOT
Operating system: Windows
Tool integration: Maven

The property dataFileIncludes in the report-aggregate can't be set by the pom file due to a known bug in maven:
[see here](https://issues.apache.org/jira/browse/MNG-5440?jql=project%20%3D%20MNG%20AND%20resolution%20%3D%20Unresolved%20AND%20text%20~%20%22%40Parameter%22%20ORDER%20BY%20priority%20DESC)

To fix this by a workaround, the default-value has to been removed from the parameter and access to it should be done by a getter which will set the default if the value is always null

### CODE REVIEW

**Comment by Godin** [comment]
@kubachmann thank you for finding this.

@marchof could you please review?

**Comment by marchof** [comment]
@Godin Ok to merge.

I only wonder whether we should have a test for this?

**Comment by Godin** [comment]
@marchof I didn't wanted to duplicate existing test and didn't managed to imagine how to update it to cover both default and custom values, so initially gave up on test. Now updated PR with new test with all customizations for `report-aggregate`.

**Comment by marchof** [comment]
@Godin Thx for taking the time to actually creating a test case! I would simplify the setup though and completely remove module child 2 here. This probably nor required to demonstrate the issue?

**Comment by Godin** [comment]
@marchof indeed - module `child2` is not required for the non-regression test for this case, however this test verifies all customizations of properties - that custom values for `dataFileExcludes` and `outputDirectory` are taken into account

**Comment by marchof** [comment]
@Godin Of course you're right. Now I see the use case for child2. Sorry.

**Comment by marchof** [comment]
So, looks good to me!

**Pull request merged**
