### PR TITLE
Show message in HTML report when source file can't be found

### PR DESCRIPTION
**Pull request by Godin**
One of common problems already described in [our FAQ](https://www.jacoco.org/jacoco/trunk/doc/faq.html) and still frequently faced by users - incorrect location of source files, which leads to absence of pages with sources in HTML report:

* https://stackoverflow.com/a/53833558/244993
* https://groups.google.com/d/msg/jacoco/wmwYxLKKn3Q/5AH5qSGBDgAJ
* https://github.com/jacoco/jacoco/issues/787#issuecomment-437578208
* https://github.com/jacoco/jacoco/issues/751#issuecomment-414480178

So I propose to add following message to a page with class methods

```
Source file `org/example/Example.java` was not found during generation of report.
```

### CODE REVIEW

**Comment by Godin** [comment]
> But what if users do not provide source file at all (e.g. because they don't have it). In this case the same message would still be included in the report.

@marchof I don't think that this little hint will bother such users.

**Comment by marchof** [comment]
@Godin In this case there are more common problems where we can add a hint to report:

* Only class with different class id found
* Class files without debug information

I would prefer to put the checks and message construction to a seperate, testable class `DiagnosticsInfo`.

**Comment by Godin** [comment]
> In this case there are more common problems where we can add a hint to report:
> * Only class with different class id found
> * Class files without debug information

@marchof baby steps, I was planning to add these via follow-up PRs 😉 

> I would prefer to put the checks and message construction to a seperate, testable class `DiagnosticsInfo`.

Did I get it right - you just wanna pull entire `if` into separate class? i.e. without removal of dependency on `HTMLElement body` and `ILinkable sourcePage` ?

**Comment by marchof** [comment]
@Godin I haven't thought about the design in detail. My idea is to encapsulate the checks and the creation of warnings (as html elements) in a separate class. So for example the hint for missing line information can be shown on different page types.

**Comment by Godin** [comment]
@marchof I agree with idea :thumbsup: Other than simple `if` extraction, design looks foggy to me for the time being because this message targets only single page. This message alone IMO is already quite valuable, so I'd like to propose merge as is and I'll work on addition of other messages and thus on the re-design in a next PR. Missing unit tests were added.

**Comment by Godin** [comment]
BTW should be noted that there are actually three cases of

> Class files without debug information

* `javac -g:source` produces only `SourceFile` attribute - line coverage can not be computed, however can link with source file without highlighting 😆 
* `javac -g:lines` produces only `LineNumberTable` attribute - line coverage can be computed, but can not link with source file
* `javac -g:none` - no debug information at all

**Pull request merged**
