### PR TITLE
Get rid of DNS request in DumpTaskTest

### PR DESCRIPTION
**Pull request by Godin**
This PR covers case described in https://github.com/jacoco/jacoco/pull/300#issuecomment-221838166

### CODE REVIEW

**Comment by Godin** [comment]
@timp please check whether this works for you

**Comment by timp** [comment]
I turned BT's Web Address Help http://preferences.webaddresshelp.bt.com/selfcare/preferences.cgi back on so that 
```
$ ping unknown
PING unknown (92.242.132.15) 56(84) bytes of data.
^C
--- unknown ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2028ms

```
then 
```
$ cd jacoco/org.jacoco.ant
$ mvn clean install
....
[INFO] BUILD SUCCESS
```
however 
```
$ cd ..
$ mvn install
```
gives 
```
testUnknownHost:
[jacoco:dump] Connecting to nosuchhost/92.242.132.15:6300
[jacoco:dump] Connection timed out
[jacoco:dump] Connecting to nosuchhost/92.242.132.15:6300
[jacoco:dump] Connection refused
[jacoco:dump] Connecting to nosuchhost/92.242.132.15:6300
[jacoco:dump] Connection refused
[jacoco:dump] Connecting to nosuchhost/92.242.132.15:6300
[jacoco:dump] Connection refused
[jacoco:dump] Connecting to nosuchhost/92.242.132.15:6300
```
applying your change above
```
$ mvn clean install
```
gives
```
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13:06 min
[INFO] Finished at: 2016-05-26T23:39:48+01:00
[INFO] Final Memory: 117M/922M
[INFO] ------------------------------------------------------------------------
```
Hooray!
Now to turn Web Address Help back off before it bites me again.

**Comment by Godin** [comment]
@marchof could you please review?

**Comment by marchof** [comment]
Works for me too! Thx.

**Pull request merged**
