### PR TITLE
Adds common use cases of questions/problems to README

### PR DESCRIPTION
**Pull request by asm0dey**

### CODE REVIEW

**Comment by marchof** [comment]
Hi, I like the concise use case based format and would also replace the two preceding paragraphs with it. I miss some important links, also some use cases may have more links:

* I want to know how JaCoCo works --> Documentation
* I have a question --> FAQ, Documentation, Mailing List

**Comment by marchof** [comment]
Proposal:

-------

JaCoCo Java Code Coverage Library
=================================

[Build Status](https://dev.azure.com/jacoco-org/JaCoCo/_build/latest?definitionId=1&branchName=master)
[Build status](https://ci.appveyor.com/project/JaCoCo/jacoco/branch/master)
[Maven Central](http://search.maven.org/#search|ga|1|g%3Aorg.jacoco)

JaCoCo is a free Java code coverage library distributed under the Eclipse Public
License.

## Starting Points

- I want to use JaCoCo &rarr; [Download](https://www.jacoco.org/jacoco/), [Maven](https://www.jacoco.org/jacoco/trunk/doc/maven.html), [Ant](https://www.jacoco.org/jacoco/trunk/doc/ant.html), [CLI](https://www.jacoco.org/jacoco/trunk/doc/cli.html), [Other](https://www.jacoco.org/jacoco/trunk/doc/integrations.html)
- I want to know how JaCoCo works &rarr; [Documentation](http://www.jacoco.org/jacoco/trunk/doc/)
- I have question &rarr; [FAQ](http://www.jacoco.org/jacoco/trunk/doc/faq.html), [Documentation](http://www.jacoco.org/jacoco/trunk/doc/), [User Forum](https://groups.google.com/forum/?fromgroups=#!forum/jacoco)
- I found a bug &rarr; [Bug Report](https://github.com/jacoco/jacoco/issues/new/choose)
- I have an idea &rarr; [User Forum](https://groups.google.com/forum/?fromgroups=#!forum/jacoco), [Feature Request](https://github.com/jacoco/jacoco/issues/new/choose)

**Comment by asm0dey** [comment]
Thanks for the feedback, Marc, I will improve the PR today.

**Comment by marchof** [comment]
If you agree I can just commit my proposal to your PR.

**Comment by asm0dey** [comment]
Of course! Thank you very much for your work!

**Comment by marchof** [comment]
Sorry, I can't push to your branch. You may want to enable it or just pick my proposal above.

**Comment by asm0dey** [comment]
OK, for an unknown reason, I can't accept the proposal not only from my smartphone but also from the desktop. I'll update it manually now

**Review by marchof — APPROVED** [review]

**Comment by Godin** [comment]
@asm0dey thanks! ❤️

**Pull request merged**
