### PR TITLE
Added coverage export to MongoDB

### PR DESCRIPTION
**Pull request by ihr**
Hi guys,

I've added an export to MongoDB in order to facilitate (microservice) coverage report generation/exportation when app is deployed in a Cloud.

Please, let me know what  you think.

### CODE REVIEW

**Comment by marchof** [comment]
I don't think JaCoCo should get an dependency on MongoDB. As you can see from the build status the build failed as JaCoCo's minimum Java version is 1.5. MongoDB seems to be 1.6.

-1 sorry

**Comment by marchof** [comment]
I would rather go e.g. for a proxy e.g. serves as a JaCoCo TCP Server and dumps incoming requests to a MongoDB instance. Anyways this would be a separate project.

**Comment by ihr** [comment]
That was my initial thought still, I had some problems with the TCP server. Will dig further and if suitable create a proxy project.

Cheers

**Comment by marchof** [comment]
The ExecutionDataServer example should be a good starting point:

http://eclemma.org/jacoco/trunk/doc/examples/java/ExecutionDataServer.java

**Comment by ihr** [comment]
Thanks, much appreciated! A problem concerning the proxy approach is that most often network connectivity among cloud processes is via HTTP/S.

**Comment by marchof** [comment]
Well, but mongoDB also uses a plain TPC connection. So what is the difference here to this PR?

**Comment by ihr** [comment]
I was thinking of an approach over HTTP/S, no the one using MongoDB sink. Since you said that you don't like having an additional dependency.

**Pull request closed without merging**
