### PR TITLE
Expand Expression in propertyName

### PR DESCRIPTION
**Pull request by FulaiZhang-cn**
a minor improvment for `jacoco-maven-plugin` to support expand expression in `argLine`.

for maven project, developer may want use expression in `argLine` (the default `propertyName`), for example:

```
<properties>
     <argLine>-javaagent:${settings.localRepository}/co/paralleluniverse/quasar-core/0.7.5/quasar-core-0.7.5-jdk8.jar</argLine>
</properties>
```

there contains expression `${settings.localRepository}`.
as before, jacoco-maven-plugin simply append it to jacoco agent arguments, like this: 

```
argLine set to -javaagent:F:\\env\\repository\\org\\jacoco\\org.jacoco.agent\\0.8.3-SNAPSHOT\\org.jacoco.agent-0.8.3-SNAPSHOT-runtime.jar=destfile=F:\\Platform2\\platform-config\\target\\jacoco-it.exec -javaagent:${settings.localRepository}/co/paralleluniverse/quasar-core/0.7.5/quasar-core-0.7.5-jdk8.jar
```

after that, maven-surefire-plugin will immediate use this `argLine`, without expended expression. this will cause issue. another solution is use different `propertyName` for  `jacoco-maven-plugin` and `maven-surefire-plugin`, for example:

```
<properties>
     <argLine>-javaagent:${settings.localRepository}/co/paralleluniverse/quasar-core/0.7.5/quasar-core-0.7.5-jdk8.jar</argLine>
</properties>
<plugin>
                        <groupId>org.jacoco</groupId>
                        <artifactId>jacoco-maven-plugin</artifactId>
                        <version>0.8.2</version>
                        <configuration>
                            <propertyName>jacocoAgent</propertyName>
                        </configuration>
</plugin>
<plugin>
                        <groupId>org.apache.maven.plugins</groupId>
                        <artifactId>maven-surefire-plugin</artifactId>
                        <configuration>
                            <argLine>@{jacocoAgent} ${argLine}</argLine>
                        </configuration>
</plugin>
```

this is work well for maven, but IDE not support `@{...}` expression yet, when using IDE to run test, it failed.

seems the better solution is let `jacoco-maven-plugin` support expend expression.

### CODE REVIEW

**Comment by FulaiZhang-cn** [comment]
@marchof  I don't know which version we should use?
seems the new dependency cause CI failed.
<dependency>
      <groupId>org.apache.maven</groupId>
      <artifactId>maven-core</artifactId>
      <version>3.0</version>
</dependency>

**Comment by Godin** [comment]
> seems the new dependency cause CI failed

Seems that CI failure was temporary, as a possible wild guess - corrupted files e.g. due to network issues.

> I don't know which version we should use?

This raises serious doubts about correctness of approach/changes in general.

IMO to increase speed and chances of acceptance of this change you need to answer this question by yourself.

Not even mentioning that added code seems to be not covered by tests. As you obviously care about test coverage, why do you think test coverage is not relevant for the JaCoCo project? 😉 

Unfortunately right now I don't have time to dig more into this, however here is quick note as an attempt to help you answer this question: IMO addition of dependency on `maven-core` **version 3.0** implies break of compatibility with currently targeted Maven **version 2.2.1** (#194). Can required classes be found in Maven 2.2.1 ? Maybe name of dependency or package was changed between these versions ?

**Comment by Godin** [comment]
Furthermore:

> IDE not support @{...}

Which IDE ?

> seems the better solution is let jacoco-maven-plugin support expend expression

Aren't better to fix IDE ? Or maybe there are other benefits of this change that I miss ? 😉 

And BTW can `prepare-agent` be replaced by a similar thing that you do for `quasar-core` as a workaround ?

**Comment by Godin** [comment]
@FulaiZhang-cn FIY #194 has been resolved. Any chance that you'll answer remaining questions here?

**Comment by FulaiZhang-cn** [comment]
> IDE
 Intellij 2018 on Windows 7 (64 bit)
> Aren't better to fix IDE ?  
Our company have many developer, it's not simple to solve this issue, some guys use Eclipse and other guys use Intellij, they use OSX, Ubuntu or Windows.
IMO the argline is changed by JaCoCo, so it's JaCoCo's responsibility to keep argline work as developer expected.

**Comment by FulaiZhang-cn** [comment]
'PluginParameterExpressionEvaluator'  can found in 'Maven version 2.2.1'
I will modify my code.

**Comment by Godin** [comment]
> IMO the argline is changed by JaCoCo, so it's JaCoCo's responsibility to keep argline work as developer expected.

This is a way too strong statement, because the following `pom.xml` that **doesn't contain `jacoco-maven-plugin`** at all

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <jvmArgs></jvmArgs>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
        <configuration>
          <argLine>@{jvmArgs}</argLine>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

doesn't work in IntelliJ 2018.2 producing for any test

```
Error: Could not find or load main class @{jvmArgs}
```

whereas perfectly works in command line.

----

Also for the following `pom.xml` that **doesn't contain `jacoco-maven-plugin`** at all

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <argLine>-DmavenRepository=${settings.localRepository}</argLine>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
      </plugin>
    </plugins>
  </build>
</project>
```

and `src/test/java/ExampleTest.java`

```
public class ExampleTest {
  @org.junit.Test
  public void test() {
    System.out.println("mavenRepository: " + System.getProperty("mavenRepository"));
    System.out.println("qualifier: " + System.getProperty("qualifier"));
  }
}
```

execution of `mvn test` from command line produces

```
[INFO] Running PrintMavenRepositoryTest
mavenRepository: /Users/evgeny.mandrikov/.m2/repository
qualifier: null
```

whereas execution of `ExampleTest` in IntelliJ 2018.2 produces

```
mavenRepository: null
qualifier: null
```

----

Also for the following `pom.xml` that **doesn't contain `jacoco-maven-plugin`** at all

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <jvmArgs>-Dqualifier=${parsedVersion.qualifier} -DmavenRepository=${settings.localRepository}</jvmArgs>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>parse-version</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
        <configuration>
          <argLine>${jvmArgs}</argLine>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

execution of `mvn test` from command line produces

```
[INFO] Running PrintMavenRepositoryTest
mavenRepository: /Users/evgeny.mandrikov/.m2/repository
qualifier: SNAPSHOT
```

whereas execution of `ExampleTest` in IntelliJ 2018.2 again produces

```
mavenRepository: null
qualifier: null
```

So who is breaking developer expectations? :wink:

----

The last example is essentially

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <jvmArgs>${jacocoAgent} -DmavenRepository=${settings.localRepository}</jvmArgs>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.2</version>
        <executions>
          <execution>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
            <configuration>
              <propertyName>jacocoAgent</propertyName>
            </configuration>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
        <configuration>
          <argLine>${jvmArgs}</argLine>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

for which IntelliJ 2018.2 again behaves differently from the command line execution.

And proposed change does not help at all.

----

Furthermore please consider scenarios where between `jacoco-maven-plugin` and `maven-surefire-plugin` there is another plugin that operates with properties. For example

for the following `pom.xml`

```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.example</groupId>
  <artifactId>example</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

    <argLine>-Dqualifier=${parsedVersion.qualifier}</argLine>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.12</version>
      <scope>test</scope>
    </dependency>
  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.jacoco</groupId>
        <artifactId>jacoco-maven-plugin</artifactId>
        <version>0.8.2</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>prepare-agent</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>build-helper-maven-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <phase>initialize</phase>
            <goals>
              <goal>parse-version</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.22.1</version>
      </plugin>
    </plugins>
  </build>
</project>
```

execution of `mvn test` currently results in

```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------< org.example:example >-------------------------
[INFO] Building example 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (default) @ example ---
[INFO] argLine set to -javaagent:/Users/evgeny.mandrikov/.m2/repository/org/jacoco/org.jacoco.agent/0.8.2/org.jacoco.agent-0.8.2-runtime.jar=destfile=/private/tmp/issue-785/target/jacoco.exec -Dqualifier=${parsedVersion.qualifier}
[INFO]
[INFO] --- build-helper-maven-plugin:3.0.0:parse-version (default) @ example ---
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/issue-785/src/main/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ example ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ example ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /private/tmp/issue-785/src/test/resources
[INFO]
[INFO] --- maven-compiler-plugin:3.1:testCompile (default-testCompile) @ example ---
[INFO] Nothing to compile - all classes are up to date
[INFO]
[INFO] --- maven-surefire-plugin:2.22.1:test (default-test) @ example ---
[INFO]
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running ExampleTest
mavenRepository: null
qualifier: SNAPSHOT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.122 s - in ExampleTest
[INFO]
[INFO] Results:
[INFO]
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.222 s
[INFO] Finished at: 2019-01-21T19:09:14+01:00
[INFO] ------------------------------------------------------------------------
```

Whereas **this will not work, if expansion will be done as you propose during execution of `prepare-agent` that is executed before `build-helper-maven-plugin:parse-version`**.

Not even counting that currently proposed changes cause NPE in such case:

```
Caused by: java.lang.NullPointerException
    at org.jacoco.maven.AbstractAgentMojo.expandExpression (AbstractAgentMojo.java:183)
```

----

I can understand that

> it's not simple to solve this issue by update IDE

But from the above IMO clear that the root of the problem is in IntelliJ and not at all in `jacoco-maven-plugin`. And while proposal maybe can help in your case, it also clearly will breaks others, without solving the root problem.

And while waiting for proper fix in IntelliJ as was already asked in https://github.com/jacoco/jacoco/pull/785#issuecomment-452124261

> can prepare-agent be replaced by a similar thing that you do for quasar-core as a workaround ?

or by using profiles - e.g. one default for IDE and one for CI with JaCoCo?

**Comment by Godin** [comment]
Looks like ticket on IntelliJ side already exists - https://youtrack.jetbrains.net/issue/IDEA-204155

**Pull request closed without merging**
