### PR TITLE
Allow filtering of specific methods in Java #993

### PR DESCRIPTION
**Pull request by better-712**
it can pass through coverage for toString method for need

### CODE REVIEW

**Comment by marchof** [comment]
Filtering all methods called "toString" is not a feature we consider to include.

**Comment by better-712** [comment]
Thanks for your reply, Should the issue #993 also be closed?



---Original---
From: "Marc R. ***@***.***&gt;
Date: Mon, May 30, 2022 00:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jacoco/jacoco] Allow filtering of specific methods in Java #993 (PR #1320)




 
Filtering all methods called "toString" is not a feature we consider to include.

**Comment by better-712** [comment]
Thanks for your reply, should the issue #993 also be closed?



---Original---
From: "Marc R. ***@***.***&gt;
Date: Mon, May 30, 2022 00:57 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jacoco/jacoco] Allow filtering of specific methods in Java #993 (PR #1320)




 
Filtering all methods called "toString" is not a feature we consider to include.

**Comment by marchof** [comment]
@better-712 I assume that #993 would be a config option (not hard coded like in this PR). But as we decided not to make filtering configurable the issue should be closed. Thanks for the hint!

**Pull request closed without merging**
