### PR TITLE
Add experimental support for Java 11 class files

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by marchof** [comment]
@Godin Is there a reason that we use native ASM support for Java 11 but still use the `BytecodeVersion` trick for Java 10?

**Comment by marchof** [comment]
@Godin I found two more places where the new Java version should be added:

* `InstrSupportTest.needFrames_should_return_true_for_versions_greater_than_or_equal_to_1_6()`
* `ClassFileVersionsTest`

**Comment by Godin** [comment]
@marchof updated `InstrSupportTest` and `ClassFileVersionsTest`. IMO we should find a way to reduce number of places that require non functional mechanical update.

Cleanup from `V10` is unrelated to Java 11, so will do it separately.

**Comment by marchof** [comment]
@Godin You're right about reducing numbers of places, where we encode class file versions. Maybe something like

    int[] SUPPORTED_VERSIONS;

in `BytecodeVersion` could be a solution.

**Pull request merged**
