### PR TITLE
add filter: GetterAndSetterFilter

### PR DESCRIPTION
**Pull request by donhui**
add filter: GetterAndSetterFilter

### CODE REVIEW

**Comment by marchof** [comment]
@donhui Thanks for this contribution! Filtering user code is very controversial. Therefore we decided not to include them in JaCoCo. It will simply cause too many discussions with our users which we can't handle with our limited resources. Therefore we currently only focus on filtering compiler generated synthetic code.

Also as you can see from the broken build, getting filters right is a cumbersome task. Your filter breaks an Kotlin integration test.

Thanks for your understanding!

**Comment by donhui** [comment]
I wonder why my filter breaks an Kotlin integration test. 
Because I never change the Kotlin code.

**Comment by marchof** [comment]
Probably because your filter has side effects on filtering of classfiles generated by the Kotlin compiler?

We have lots of integration tests for different JVM languages. Actually there should also be one for your filter.

But as said before: We will curretnly not include user code filtering.

**Comment by donhui** [comment]
> Probably because your filter has side effects on filtering of classfiles generated by the Kotlin compiler?
> 
> We have lots of integration tests for different JVM languages. Actually there should also be one for your filter.
> 
> But as said before: We will currently not include user code filtering.

I see. Thank you！

**Comment by asolntsev** [comment]
We would like to filter out getters/setters because of Kotlin. 
In Kotlin, we have `data` classes which have generated getters/setters. We don't want to test them neither see those "uncovered" lines in JaCoCo report. 

@donhui

**Comment by donhui** [comment]
@asolntsev 
you can reference the code of this PR, then custom your jacoco jar and related plugins.

**Comment by asolntsev** [comment]
@donhui thank you, I know that in open-source world it's always possible to fork&customize :)

But for most of users, it's too hard way.

**Pull request closed without merging**
