### PR TITLE
Add test of offline instrumentation of Java 9 module-info

### PR DESCRIPTION
**Pull request by Godin**

### CODE REVIEW

**Comment by marchof** [comment]
@Godin I wonder how this test relates to the Maven plug-in. It's more like a JaCoCo code issue. Maybe it is time to create a new source folder

    org.jacoco.core.test/src-java9

and move the test there?

**Comment by Godin** [comment]
@marchof you're right that test is not directly related to Maven plugin, however we can't simply add `module-info.java` into `org.jacoco.core.test` because then compilation will fail with many errors - for example one of them
```
org.jacoco.core.test/src/org/jacoco/core/test/validation/SourceTest.java:[14,24] package org.junit does not exist
```
i.e. dependencies should be modules too, which is not the case at least for `junit`, not counting other issues with modularization such as "package exists in another module: org.jacoco.core".

Also runtime issues such as #545 won't be visible if we'll verify only offline instrumentation of `module-info.class` without execution, whereas I planned to update this end-to-end test to also demonstrate #545 and how to deal with it in Maven.

So not counting commit of already compiled `module-info` that I don't like for three reasons: addition of binary file, will not be testing further versions of compiler and will not be testing end-to-end user experience that includes execution. The only simple way to test instrumentation of compiled `module-info` that I found - is to add integration test of Maven plugin.

**Comment by Godin** [comment]
@marchof 

> I wonder whether there should be some some verification? Or is it that there is no error?

without
```xml
              <!-- FIXME remove this workaround after update of ASM to 6.0 -->
              <excludes>
                <exclude>module-info.class</exclude>
              </excludes>
```
in `pom.xml` build will fail with `NullPointerException` as described in #544. Thus, yes, verification - is that build completes successfully.

**Comment by Godin** [comment]
To be even more precise: currently this test doesn't demonstrate #545, because use of `--module-path` not yet implemented in `maven-surefire-plugin` (https://issues.apache.org/jira/browse/SUREFIRE-1262), but as was said before - demonstrates #544.

**Comment by marchof** [comment]
@Godin Ok, thanks for the explanation!

**Pull request merged**
