### PR TITLE
Visual cleanup of JDK/compilation target table

### PR DESCRIPTION
**Pull request by marchof**
While reviewing #1033 I had a hard time again to read the JDK/classfile matrix in our build documentation (source as well as rendered html). I propose rework the matrix:

* Use default table style
* Remove redundant classfile version
* Repeat and shorten cells to archieve visual grid

### CODE REVIEW

**Comment by bmhm** [comment]
@marchof  could you add two screenshots? Before and after? I think this will help getting this PR merged. 
That's just a random tought, though. ;-)

**Comment by Godin** [comment]
Before

before

After

after

**Comment by marchof** [comment]
@Godin Thx!

**Comment by bmhm** [comment]
Thanks! I highlighted this, because I am really looking forward to 0.8.6: It enables default method coverage. This was one of four remaining issues/PRs for that particular milestone.
Thanks for merging! :)

**Pull request merged**
