### PR TITLE
Upgrading Scala validation tests to Scala 2.13.4

### PR DESCRIPTION
**Pull request by gergelyfabian**
This is the latest version from Scala 2.12 series.

### CODE REVIEW

**Comment by Godin** [comment]
Hi @gergelyfabian First of all - thank you for your contribution!

----

> This is the latest version from Scala 2.12 series.

As @marchof wrote in https://github.com/jacoco/jacoco/pull/1136#issuecomment-747219228

>  we decided to support only latest releases for non-Java languages

So I'm wondering what are the reasons to stay with 2.12.x series? Why not upgrade to 2.13.4 ?

**Comment by gergelyfabian** [comment]
> Hi @gergelyfabian First of all - thank you for your contribution!
> 
> > This is the latest version from Scala 2.12 series.
> 
> As @marchof wrote in [#1136 (comment)](https://github.com/jacoco/jacoco/pull/1136#issuecomment-747219228)
> 
> > we decided to support only latest releases for non-Java languages
> 
> So I'm wondering what are the reasons to stay with 2.12.x series? Why not upgrade to 2.13.4 ?

Only personal. I use Scala 2.11 and 2.12 and the projects I'm interested in (Spark mainly) use still Scala 2.12 (https://spark.apache.org/docs/3.0.0-preview/). Scala 2.12 still seems to be the most widely used Scala version.

However, if you feel that indeed Scala should be upgraded in Jacoco to 2.13, then I'll just keep a branch in my fork where I'll keep testing also Scala 2.12 and 2.11 just out of curiosity, as I need to use Jacoco with those versions.

**Comment by gergelyfabian** [comment]
Ok, I'll change this PR to upgrade to Scala 2.13.4. I'll deal with Scala 2.12 and 2.11 in my fork.

**Comment by gergelyfabian** [comment]
PR changed to upgrade to Scala 2.13.

**Review by marchof — APPROVED** [review]

**Comment by Godin** [comment]
For consistency with `org.jacoco.core.test.validation.groovy` and `org.jacoco.core.test.validation.kotlin` I added property `scala.version`

@gergelyfabian Hope that this also will be helpful for testing of different Scala versions in your fork :wink:

**Review by Godin — APPROVED** [review]

**Pull request merged**
