### PR TITLE
Add validation test for groovy.transform.Sortable

### PR DESCRIPTION
**Pull request by sclassen**
The test is currently failing and an appropriate issue is open at
https://issues.apache.org/jira/browse/GROOVY-9125

### CODE REVIEW

**Comment by Godin** [comment]
https://issues.apache.org/jira/browse/GROOVY-9125 states

> This static block is shown by jacoco as not covered with test.

which is wrong: while static initializer does not have `Generated` annotation, it is marked as covered, because it is executed during class loading

GroovySortableClassTarget

Assertion verifies number of methods and does not verify whether methods are marked as covered or not.

**Comment by sclassen** [comment]
@Godin thx for the clarification.
I updated the groovy issue and included your screenshot

**Comment by Godin** [comment]
@sclassen I'm not sure about validity of GROOVY-9125 in general:

Generated part already shows up as covered. And more importantly consider following source code

```
@groovy.transform.Sortable
class GroovySortableClassTarget {

    static {
        println "Hello, world!"
    }

    String first

}
```

which leads to bytecode with following static initializer

```
  static {};
    descriptor: ()V
    flags: ACC_STATIC
    Code:
      stack=3, locals=1, args_size=0
         0: invokestatic  #27                 // Method $getCallSiteArray:()[Lorg/codehaus/groovy/runtime/callsite/CallSite;
         3: ldc           #39                 // int 0
         5: aaload
         6: ldc           #41                 // class org/jacoco/core/test/validation/groovy/targets/GroovySortableClassTarget$FirstComparator
         8: invokeinterface #47,  2           // InterfaceMethod org/codehaus/groovy/runtime/callsite/CallSite.callConstructor:(Ljava/lang/Object;)Ljava/lang/Object;
        13: astore_0
        14: aload_0
        15: ldc           #49                 // class java/util/Comparator
        17: invokestatic  #55                 // Method org/codehaus/groovy/runtime/ScriptBytecodeAdapter.castToType:(Ljava/lang/Object;Ljava/lang/Class;)Ljava/lang/Object;
        20: checkcast     #49                 // class java/util/Comparator
        23: putstatic     #57                 // Field this$FirstComparator:Ljava/util/Comparator;
        26: aload_0
        27: pop
        28: invokestatic  #27                 // Method $getCallSiteArray:()[Lorg/codehaus/groovy/runtime/callsite/CallSite;
        31: ldc           #58                 // int 1
        33: aaload
        34: ldc           #2                  // class org/jacoco/core/test/validation/groovy/targets/GroovySortableClassTarget
        36: ldc           #60                 // String Hello, world!
        38: invokeinterface #64,  3           // InterfaceMethod org/codehaus/groovy/runtime/callsite/CallSite.callStatic:(Ljava/lang/Class;Ljava/lang/Object;)Ljava/lang/Object;
        43: pop
        44: return
      LineNumberTable:
        line 29: 28
        line 30: 44
```

in this case it is incorrect to mark static initializer as `Generated` because it contains non-generated handwritten code.

**Comment by sclassen** [comment]
Totally agree with you example.
As I am neither a groovy nor a jacoco committer I'm kind of unsure what the correct behavior would be.
Do you have a suggestion?

**Comment by Godin** [comment]
@sclassen leave as it is currently and close GROOVY-9125 without modifications as invalid:
Completely generated static initializer IMO does not bother, because will be shown as covered as soon as class is initialized. And possible to see non-generated part of static initializer if there is any.

Also let's notify @aalmiray who started all this: please take care to not mark methods as `Generated` if they contain handwritten code or can contain as in this example of static initializer.

**Comment by Godin** [comment]
And assertion here can be simply fixed as following
```diff
     @Test
     public void test_method_count() {
-        assertMethodCount(1);
+        assertMethodCount(2);
     }
```

**Comment by aalmiray** [comment]
I think that adding `@Generated` to a static initializer is not a good idea. Closing GROOVY-9125 would be the way to go IMHO.

**Comment by sclassen** [comment]
Groovy issue has been closed and the tests adapted to pass.
I think this is ready to be merged once #863 has been merged

**Comment by Godin** [comment]
@sclassen thanks! I'll work on merging both tomorrow - too tired for today 😪

**Comment by Godin** [comment]
@sclassen merged. Thank you for your contribution! ❤️

**Pull request merged**
