### PR TITLE
"m2e/lifecycle-mapping-metadata.xml" should include "report-aggregate"

### PR DESCRIPTION
**Pull request by Godin**
In #388 we forgot to do this.

### CODE REVIEW

**Comment by Godin** [comment]
@marchof could you please review?

**Comment by marchof** [comment]
@Godin Thanks!

**Comment by syashwanthk** [comment]
Hi, Can I please know whether the feature from the change log as "New Maven goal report-aggregate to create reports for multi-module projects (GitHub #388)." help in just aggregating coverage reports of all modules into single one only or also helps in "generating aggregate-report that reports cross module code coverage for the maven plugin"?

**Comment by Godin** [comment]
@syashwanthk Hi, please use our mailing list ( https://groups.google.com/forum/#!forum/jacoco ) for questions instead of commenting on unrelated tickets. Thank you for your understanding.

Answering your question: it does both.

**Comment by syashwanthk** [comment]
Apologies for the same. Thanks for your reply.

**Pull request merged**
